controllerMode: in-cluster
dependencies:
  local:
    kubeconfigPath: ""
    prometheusURL: "http://localhost:9090"
  inCluster:
    prometheusURL: ""
executionMode: controller
controller:
  targetNamespace: ""
  targetClusterID: ""
  writeAuthorizedClusters: []
  tasks:
    createStats:
      enabled: false
      schedule: "15m"
      metadata:
        skipMemory: false
    applyRecommendation:
      enabled: false
      schedule: "5m"
      metadata:
        dryRun: true
        skipMemory: false
        nodeStatsURL:
          host: "http://localhost:8080"
        overridesURL:
          host: "http://localhost:8080"
    modifyEqualCPUResources:
      enabled: false
      schedule: "10m"
    nodeLoadMonitoring:
      enabled: false
      schedule: "60s"
    fetchMetrics:
      enabled: false
      schedule: "1m"
    cleanupOOMEvent:
      enabled: false
      schedule: "24h"
      metadata:
        retentionDays: 7
metrics:
  enabled: true
  port: "8081"   
server:
  port: "8080"
  basicAuth:
    username: "admin"
    password: "admin"
webhook:
  port: "8443"
  certsDir: "/tmp/webhook-certs"
  dryRun: true
  statsURL:
    host: "http://localhost:8080"
    tfyClusterToken: "<cluster-token>"
# db:
#   type: sqlite
#   database: "stats-data/cruisekube.db"
db:
  type: postgres
  host: localhost
  port: 5432
  database: cruisekube
  username: cruisekube
  password: cruisekube
  sslmode: disable
recommendationSettings:
  newWorkloadThresholdHours: 1
  disableMemoryApplication: true
  applyBlacklistedNamespaces: []
  maxConcurrentQueries: 30
  oomCooldownMinutes: 5
telemetry:
  enabled: false
  exporterOTLPEndpoint: ""
  exporterOTLPHeaders: ""
  serviceName: ""
  traceRatio: 0.1
