{{- if include "cruisekube.postgresqlLocalEnabled" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cruisekube.fullname" . }}-postgresql-secret
  labels:
    {{- include "cruisekube.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  password: {{ .Values.postgresql.local.password | b64enc | quote }}
{{- end }}
