{{- if .Values.autopilot-controller.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "autopilot-controller.fullname" . }}
  labels:
    {{- include "autopilot-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.autopilot-controller.replicas }}
  selector:
    matchLabels:
      {{- include "autopilot-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.autopilot-controller.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "autopilot-controller.labels" . | nindent 8 }}
        {{- with .Values.autopilot-controller.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.autopilot-controller.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "autopilot-controller.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-controller
          image: "{{ .Values.autopilot-controller.image.repository }}:{{ include "autopilot-controller.imageTag" . }}"
          imagePullPolicy: {{ .Values.autopilot-controller.image.pullPolicy }}
          command: ["./autopilot"]
          args:
            - "--execution-mode=controller"
            - "--controller-mode={{ .Values.autopilot-controller.controller.mode }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 8081
              protocol: TCP
          resources:
            {{- toYaml .Values.autopilot-controller.resources | nindent 12 }}
          env:
            {{- range $key, $value := .Values.autopilot-controller.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            {{- if .Values.autopilot-controller.persistence.enabled }}
            - name: data
              mountPath: {{ .Values.autopilot-controller.persistence.mountPath }}
            {{- end }}
            {{- with .Values.autopilot-controller.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.autopilot-controller.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "autopilot-controller.fullname" . }}-data
        {{- end }}
{{- end }}
