{{- if and .Values.autopilot-controller.enabled .Values.autopilot-controller.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "autopilot-controller.fullname" . }}-data
  labels:
    {{- include "autopilot-controller.labels" . | nindent 4 }}
  {{- with .Values.autopilot-controller.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.autopilot-controller.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.autopilot-controller.persistence.size }}
  {{- if .Values.autopilot-controller.persistence.storageClass }}
  {{- if eq "-" .Values.autopilot-controller.persistence.storageClass }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.autopilot-controller.persistence.storageClass }}
  {{- end }}
  {{- end }}
{{- end }}
