{{- if and .Values.autopilot-controller.enabled .Values.autopilot-controller.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "autopilot-controller.fullname" . }}
  labels:
    {{- include "autopilot-controller.labels" . | nindent 4 }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "autopilot-controller.fullname" . }}
  labels:
    {{- include "autopilot-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "autopilot-controller.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "autopilot-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
