{{- if and .Values.autopilot-controller.enabled .Values.autopilot-controller.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "autopilot-controller.serviceAccountName" . }}
  labels:
    {{- include "autopilot-controller.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
