{{- if .Values.cruisekubeFrontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cruisekubeFrontend.fullname" . }}
  labels:
    {{- include "cruisekubeFrontend.labels" . | nindent 4 }}
  {{- with .Values.cruisekubeFrontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.cruisekubeFrontend.service.type }}
  ports:
    - port: {{ .Values.cruisekubeFrontend.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cruisekubeFrontend.selectorLabels" . | nindent 4 }}
{{- end }}

