apiVersion: 1

datasources:
  - name: Infinity-tfy-usea1-devtest
    type: yesoreyeram-infinity-datasource
    url: http://host.docker.internal:8080/clusters/tfy-usea1-devtest/workload-analysis
    isDefault: false
    editable: true
    jsonData:
      auth_method: none
      allowed_hosts: ["localhost", "127.0.0.1", "host.docker.internal"]
