apiVersion: 1

datasources:
  - name: Prometheus-tfy-usea1-devtest
    type: prometheus
    access: proxy
    url: http://host.docker.internal:8080/clusters/tfy-usea1-devtest/prometheus-proxy
    isDefault: false
    editable: true
    jsonData:
      timeInterval: 30s
      queryTimeout: 60s
      httpMethod: POST
