apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- autopilot-rbac.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: autopilot-standalone-poc
    namespace: autopilot-test
  path: serviceaccount-json-patch.yaml 