apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: autopilot-pause-daemonset
  namespace: autopilot-test
  labels:
    app: autopilot-pause-daemonset
spec:
  selector:
    matchLabels:
      app: autopilot-pause-daemonset
  template:
    metadata:
      labels:
        app: autopilot-pause-daemonset
    spec:
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.9
        command: ["/pause"]
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
          limits:
            cpu: 2m
            memory: 20Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      - operator: Exists
        effect: PreferNoSchedule
      # priorityClassName: system-node-critical
      terminationGracePeriodSeconds: 5