apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: autopilot-grafana-vs
spec:
  gateways:
  - istio-system/tfy-wildcard
  hosts:
  - autopilot-grafana.tfy-ctl-euwe1-production.production.truefoundry.com
  http:
  - route:
    - destination:
        host: autopilot-grafana.autopilot-test.svc.cluster.local
        port:
          number: 3000

