{{- if .Values.autopilot-webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "autopilot-webhook.fullname" . }}-webhook-config
  labels:
    {{- include "autopilot-webhook.labels" . | nindent 4 }}
webhooks:
- name: {{ printf "%s.%s.autopilot.truefoundry.com" (include "autopilot-webhook.fullname" .) .Release.Namespace }}
  clientConfig:
    service:
      name: {{ include "autopilot-webhook.webhookServiceName" . }}
      namespace: {{ .Release.Namespace }}
      path: {{ printf "/clusters/%s/webhook/mutate" .Values.autopilot-webhook.mutatingWebhookConfiguration.clusterID }}
      port: {{ .Values.autopilot-webhook.service.httpsPort }}
    caBundle: Cg==
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    scope: "*"
  admissionReviewVersions: ["v1"]
  sideEffects: None
  failurePolicy: {{ .Values.autopilot-webhook.mutatingWebhookConfiguration.failurePolicy }}
  reinvocationPolicy: Never
  matchPolicy: Equivalent
  timeoutSeconds: {{ .Values.autopilot-webhook.mutatingWebhookConfiguration.timeoutSeconds }}
  namespaceSelector:
    {{- include "autopilot-webhook.mutatingWebhookConfigurationNamespaceSelector" . | nindent 4 }}
  objectSelector: {}
{{- end }}
