{{- if and .Values.autopilotWebhook.enabled .Values.autopilotWebhook.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "autopilotWebhook.fullname" . }}-service-monitor
  labels:
    {{- include "autopilotWebhook.serviceMonitorLabels" . | nindent 4 }}
  {{- if .Values.autopilotWebhook.serviceMonitor.additionalAnnotations }}
  annotations:
    {{- toYaml .Values.autopilotWebhook.serviceMonitor.additionalAnnotations | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ .Values.autopilotWebhook.serviceMonitor.jobLabel }}
  selector:
    matchLabels:
      {{ include "autopilotWebhook.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  {{- toYaml .Values.autopilotWebhook.serviceMonitor.endpoints | nindent 2 }}
{{- end -}}
