{{- if and .Values.autopilot-webhook.enabled .Values.autopilot-webhook.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "autopilot-webhook.serviceAccountName" . }}
  labels:
    {{- include "autopilot-webhook.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
