{{- if .Values.autopilotWebhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "autopilotWebhook.webhookServiceName" . }}
  labels:
    {{- include "autopilotWebhook.labels" . | nindent 4 }}
  {{- with .Values.autopilotWebhook.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.autopilotWebhook.service.type }}
  ports:
    - port: {{ .Values.autopilotWebhook.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.autopilotWebhook.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "autopilotWebhook.selectorLabels" . | nindent 4 }}
{{- end }}
