{{- if and .Values.autopilotWebhook.enabled .Values.autopilotWebhook.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "autopilotWebhook.serviceAccountName" . }}
  labels:
    {{- include "autopilotWebhook.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
