apiVersion: v2
name: cruisekube
description: A Helm chart for TrueFoundry cruisekube OSS controller and webhook
type: application
version: 0.1.7
appVersion: "0.1.7"
dependencies:
  - name: postgresql
    version: "18.1.14"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
