{{- if and .Values.autopilotController.enabled .Values.autopilotController.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "autopilotController.fullname" . }}-data
  labels:
    {{- include "autopilotController.labels" . | nindent 4 }}
  {{- with .Values.autopilotController.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.autopilotController.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.autopilotController.persistence.size }}
  {{- if .Values.autopilotController.persistence.storageClass }}
  {{- if eq "-" .Values.autopilotController.persistence.storageClass }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.autopilotController.persistence.storageClass }}
  {{- end }}
  {{- end }}
{{- end }}
