{{- if .Values.autopilot-controller.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "autopilot-controller.fullname" . }}
  labels:
    {{- include "autopilot-controller.labels" . | nindent 4 }}
  {{- with .Values.autopilot-controller.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.autopilot-controller.service.type }}
  ports:
    - port: {{ .Values.autopilot-controller.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.autopilot-controller.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "autopilot-controller.selectorLabels" . | nindent 4 }}
{{- end }}
