{{- if and .Values.autopilotController.enabled .Values.autopilotController.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "autopilotController.serviceAccountName" . }}
  labels:
    {{- include "autopilotController.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
