{{- if and .Values.cruisekubeController.enabled .Values.cruisekubeController.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cruisekubeController.fullname" . }}-data
  labels:
    {{- include "cruisekubeController.labels" . | nindent 4 }}
  {{- with .Values.cruisekubeController.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.cruisekubeController.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.cruisekubeController.persistence.size }}
  {{- if .Values.cruisekubeController.persistence.storageClass }}
  {{- if eq "-" .Values.cruisekubeController.persistence.storageClass }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.cruisekubeController.persistence.storageClass }}
  {{- end }}
  {{- end }}
{{- end }}
