{{- if .Values.cruiseKubeController.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cruiseKubeController.fullname" . }}
  labels:
    {{- include "cruiseKubeController.labels" . | nindent 4 }}
  {{- with .Values.cruiseKubeController.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.cruiseKubeController.service.type }}
  ports:
    - port: {{ .Values.cruiseKubeController.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.cruiseKubeController.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "cruiseKubeController.selectorLabels" . | nindent 4 }}
{{- end }}
