{{- if and .Values.cruiseKubeController.enabled .Values.cruiseKubeController.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cruiseKubeController.serviceAccountName" . }}
  labels:
    {{- include "cruiseKubeController.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
