{{- if and .Values.cruiseKubeWebhook.enabled .Values.cruiseKubeWebhook.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cruiseKubeWebhook.fullname" . }}-service-monitor
  labels:
    {{- include "cruiseKubeWebhook.serviceMonitorLabels" . | nindent 4 }}
  {{- if .Values.cruiseKubeWebhook.serviceMonitor.additionalAnnotations }}
  annotations:
    {{- toYaml .Values.cruiseKubeWebhook.serviceMonitor.additionalAnnotations | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ .Values.cruiseKubeWebhook.serviceMonitor.jobLabel }}
  selector:
    matchLabels:
      {{ include "cruiseKubeWebhook.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  {{- toYaml .Values.cruiseKubeWebhook.serviceMonitor.endpoints | nindent 2 }}
{{- end -}}
