{{- if and .Values.cruisekubeWebhook.enabled .Values.cruisekubeWebhook.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cruisekubeWebhook.serviceAccountName" . }}
  labels:
    {{- include "cruisekubeWebhook.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
