{{- if and .Values.autopilot-webhook.enabled .Values.autopilot-webhook.certGen.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "autopilot-webhook.fullname" . }}-certgen-patch
  labels:
    {{- include "autopilot-webhook.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: {{ include "autopilot-webhook.fullname" . }}-certgen-patch
      labels:
        {{- include "autopilot-webhook.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "autopilot-webhook.certGenServiceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        fsGroup: 2000
      containers:
      - name: cert-gen
        image: {{ .Values.autopilot-webhook.certGen.image.repository }}:{{ .Values.autopilot-webhook.certGen.image.tag }}
        imagePullPolicy: {{ .Values.autopilot-webhook.certGen.image.imagePullPolicy }}
        args:
        - patch
        - --webhook-name={{ include "autopilot-webhook.fullname" . }}-webhook-config
        - --namespace={{ .Release.Namespace }}
        - --secret-name={{ include "autopilot-webhook.tlsSecretName" . }}
        - --patch-validating=false
        - --log-level=debug
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        resources:
          {{- toYaml .Values.autopilot-webhook.certGen.resources | nindent 10 }}
{{- end }}
