{{- if and .Values.autopilot-webhook.enabled .Values.autopilot-webhook.certGen.enabled .Values.autopilot-webhook.certGen.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "autopilot-webhook.certGenServiceAccountName" . }}
  labels:
    {{- include "autopilot-webhook.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
automountServiceAccountToken: true
{{ end }}
