
{{- if and .Values.autopilotWebhook.enabled .Values.autopilotWebhook.certGen.enabled .Values.autopilotWebhook.certGen.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "autopilotWebhook.certGenServiceAccountName" . }}
  labels:
    {{- include "autopilotWebhook.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  automountServiceAccountToken: true
{{- end }}
