{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "autopilot.serviceAccountName" . }}
  labels:
    {{- include "autopilot.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
