{{- if and .Values.cruiseKubeWebhook.enabled .Values.cruiseKubeWebhook.certGen.enabled .Values.cruiseKubeWebhook.certGen.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cruiseKubeWebhook.fullname" . }}-certgen-create
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cruiseKubeWebhook.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-110"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "list", "patch", "delete", "update"]
{{- end }}
