{{- if and .Values.cruisekubeWebhook.enabled .Values.cruisekubeWebhook.certGen.enabled .Values.cruisekubeWebhook.certGen.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cruisekubeWebhook.fullname" . }}-certgen-create
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cruisekubeWebhook.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-110"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cruisekubeWebhook.fullname" . }}-certgen-create
subjects:
- kind: ServiceAccount
  name: {{ include "cruisekubeWebhook.certGenServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
