{{- if and .Values.cruisekubeWebhook.enabled .Values.cruisekubeWebhook.certGen.enabled .Values.cruisekubeWebhook.certGen.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cruisekubeWebhook.fullname" . }}-certgen-patch
  labels:
    {{- include "cruisekubeWebhook.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-110"
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "update"]
{{- end }}
