{{- if and .Values.cruisekubeWebhook.enabled .Values.cruisekubeWebhook.certGen.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cruisekubeWebhook.fullname" . }}-certgen-create
  labels:
    {{- include "cruisekubeWebhook.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: {{ include "cruisekubeWebhook.fullname" . }}-certgen-create
      labels:
        {{- include "cruisekubeWebhook.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "cruisekubeWebhook.certGenServiceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        fsGroup: 2000
      containers:
      - name: cert-gen
        image: {{ .Values.cruisekubeWebhook.certGen.image.repository }}:{{ .Values.cruisekubeWebhook.certGen.image.tag }}
        imagePullPolicy: {{ .Values.cruisekubeWebhook.certGen.image.imagePullPolicy }}
        args:
        - create
        - --host={{ include "cruisekubeWebhook.webhookServiceName" . }},{{ include "cruisekubeWebhook.webhookServiceName" . }}.{{ .Release.Namespace }}.svc,127.0.0.1,localhost
        - --namespace={{ .Release.Namespace }}
        - --secret-name={{ include "cruisekubeWebhook.tlsSecretName" . }}
        - --cert-name=tls.crt
        - --key-name=tls.key
        - --log-level=debug
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        resources:
          {{- toYaml .Values.cruisekubeWebhook.certGen.resources | nindent 10 }}
{{- end }}
