name: Scan and Generate Grype Report

on:
  schedule:
    - cron: '0 9 * * *'

jobs:
  image-scan-build-cruiseKube:
    name: Image Vulnerability Scan for Build cruiseKube
    uses: truefoundry/github-workflows-public/.github/workflows/update-grype-report.yml@main
    with:
      grype_config_file: cruiseKube-grype-config.yaml
      dockerfile_path: 'Dockerfile'
      image_artifact_name: 'cruiseKube'
      artifactory_repository_url: ${{ vars.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_REPOSITORY }}
